import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

export const metadata: Metadata = {
  title: "MISTRAL-FM — AI Radio by Mistral",
  description: "A 24/7 AI-powered radio station. Music curated by you, voices generated by Mistral Small and Voxtral TTS. Hosted by Camille & Hugo.",
  keywords: ["Mistral AI", "radio", "AI radio", "Mistral FM", "Voxtral", "music", "streaming"],
  authors: [{ name: "Mistral FM" }],
  openGraph: {
    title: "MISTRAL-FM — AI Radio by Mistral",
    description: "A 24/7 AI-powered radio station with Mistral-generated hosts.",
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "MISTRAL-FM — AI Radio by Mistral",
    description: "A 24/7 AI-powered radio station with Mistral-generated hosts.",
  },
  icons: {
    icon: [
      {
        url: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 191 135'%3E%3Cpath d='M54 0H27v27h27V0z' fill='%23FFD800'/%3E%3Cpath d='M163 0h-27v27h27V0z' fill='%23FFD800'/%3E%3Cpath d='M81 27H27v27h54V27z' fill='%23FFAF00'/%3E%3Cpath d='M163 27h-54v27h54V27z' fill='%23FFAF00'/%3E%3Cpath d='M163 54H27v27h136V54z' fill='%23FF8205'/%3E%3Cpath d='M54 81H27v27h27V81z' fill='%23FA500F'/%3E%3Cpath d='M109 81H81v27h28V81z' fill='%23FA500F'/%3E%3Cpath d='M163 81h-27v27h27V81z' fill='%23FA500F'/%3E%3Cpath d='M81 108H0v27h81v-27z' fill='%23E10500'/%3E%3Cpath d='M190 108h-81v27h81v-27z' fill='%23E10500'/%3E%3C/svg%3E",
        type: "image/svg+xml",
      },
    ],
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
        <Analytics />
      </body>
    </html>
  );
}
